name: Compile Rule-sets

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  compile-rule-sets:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        repository: SukkaLab/ruleset.skk.moe
        path: repo
        ref: master
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Preprocess JSON Rules
      run: |
        cd repo/sing-box
        for file in $(find . -type f -name '*.json'); do
          echo "Processing $file"
          python3 $GITHUB_WORKSPACE/split_process_ruleset.py "$file" "${file}.tmp"
          mv "${file}.tmp" "$file"
        done

    - name: Setup sing-box
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.12.0/sing-box_1.12.0_linux_amd64.deb"
      run: |
        set -Eeuo pipefail
        wget -O sing-box.deb $SING_BOX_DEB_URL
        sudo dpkg -i sing-box.deb
        
    - name: Compile Rule-sets
      run: |
        mkdir -p $GITHUB_WORKSPACE/non_ip $GITHUB_WORKSPACE/ip $GITHUB_WORKSPACE/domainset
        cd repo/sing-box
        for file in $(find . -type f -name '*.json'); do
          output_file="${GITHUB_WORKSPACE}/${file%.json}.srs"
          echo "Compiling $file to $output_file"
          sing-box rule-set compile --output "$output_file" "$file"
        done
                
    - name: Clean Up
      if: always()
      run: |
        rm -rf repo
        rm -rf sing-box.deb
        
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "Update rules"
          git push
        else
          echo "No changes to commit"
        fi
